title: Naval Education and Training Command
description: Seventh Fleet Training Framework
theme: jekyll-theme-minimal
show_downloads: false

# Custom text for the large page header and footer.
header_title: Naval Education and Training Command
footer_text: Maintained by Captain Dave Gaffer for Seventh Fleet
